#!/usr/bin/env python3
"""Static trust-contract checks for the Azure Kyverno policy and fixtures.

Runs without a cluster or the Kyverno CLI. It renders the checked-in Azure
ClusterPolicy template and Helm values the same way Terraform's templatefile
does, then asserts:

  1. the policy has exactly the three trust rules;
  2. every rule uses only the Azure registry helper and the separate mutable
     Cosign metadata repository;
  3. digest-only enforcement is on (verifyDigest, required, no mutateDigest);
  4. the keyless attestor is pinned to the azure-sign-attest workflow on
     refs/heads/main with the GitHub issuer;
  5. the provenance rule's JMESPath conditions match the actual attestation
     generated by azure-sign-attest.yml (entryPoint, builder, source URI);
  6. every test-manifest container/initContainer image falls inside the
     rendered imageReferences (so the fixtures are actually evaluated by the
     policy) and no GCR/GAR registry leaked into policy or fixtures;
  7. every identity string embedded across the Azure policy, verify workflow,
     sign workflow, and static-validation workflow pins
     .github/workflows/azure-sign-attest.yml@refs/heads/main.

Run directly: python3 policy/azure/tests/check_azure_policy_contract.py
"""

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("pyyaml is required: python3 -m pip install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).resolve().parents[3]
POLICY_TEMPLATE = REPO / "policy/azure/kyverno/block-unsigned-images.yaml"
VALUES_TEMPLATE = REPO / "policy/azure/kyverno/values.yaml"
FIXTURE_DIR = REPO / "policy/azure/test-manifests"
INVALID_POLICY = REPO / "policy/azure/test-policies/invalid-trust-expectations.yaml"
IDENTITY_FILES = [
    REPO / "policy/azure/kyverno/block-unsigned-images.yaml",
    REPO / ".github/workflows/azure-verify.yml",
    REPO / ".github/workflows/azure-sign-attest.yml",
    REPO / ".github/workflows/azure-static-validation.yml",
]

# Values used to render the templates; fixtures must reference the same
# example registry/repository coordinates.
RENDER_VARS = {
    "acr_login_server": "example.azurecr.io",
    "application_repository": "supply-chain-security/supply-chain-demo",
    "cosign_repository": "supply-chain-security-attestations/supply-chain-demo",
    "kyverno_client_id": "00000000-0000-0000-0000-000000000000",
}
APP_IMAGE_PREFIX = f"{RENDER_VARS['acr_login_server']}/{RENDER_VARS['application_repository']}"
COSIGN_IMAGE_PREFIX = f"{RENDER_VARS['acr_login_server']}/{RENDER_VARS['cosign_repository']}"

failures = []


def check(condition: bool, message: str) -> None:
    if condition:
        print(f"OK: {message}")
    else:
        failures.append(message)
        print(f"FAIL: {message}", file=sys.stderr)


def render_template(path: Path) -> str:
    text = path.read_text()
    for key, value in RENDER_VARS.items():
        text = text.replace("${" + key + "}", value)
    leftover = re.findall(r"\$\{[a-zA-Z_]+\}", text)
    check(not leftover, f"{path.name} renders without unresolved placeholders ({leftover or 'none left'})")
    return text


def main() -> int:
    policy = yaml.safe_load(render_template(POLICY_TEMPLATE))
    values = yaml.safe_load(render_template(VALUES_TEMPLATE))

    # 1. Rule set
    rules = {rule["name"]: rule for rule in policy["spec"]["rules"]}
    check(
        set(rules)
        == {"verify-image-signature", "verify-sbom-attestation", "verify-provenance-attestation"},
        "policy contains exactly the three trust rules",
    )
    check(
        policy["spec"]["validationFailureAction"] == "Enforce",
        "policy action is Enforce",
    )

    expected_entrypoint = ".github/workflows/azure-sign-attest.yml"
    expected_identity_suffix = f"{expected_entrypoint}@refs/heads/main"
    expected_issuer = "https://token.actions.githubusercontent.com"

    for name, rule in rules.items():
        verify = rule["verifyImages"][0]
        # 2. Azure helper + separate metadata repository
        check(
            verify.get("imageRegistryCredentials", {}).get("helpers") == ["azure"],
            f"{name}: only the Azure registry helper is used",
        )
        check(
            verify.get("repository") == RENDER_VARS["cosign_repository"],
            f"{name}: signatures/attestations resolve in the separate Cosign metadata repository",
        )
        # 3. Digest-only enforcement
        check(verify.get("verifyDigest") is True, f"{name}: verifyDigest is true")
        check(verify.get("required") is True, f"{name}: verification is required")
        check(verify.get("mutateDigest") is False, f"{name}: mutateDigest is false")
        # 4. Keyless attestor pinning
        for attestors in verify.get("attestors", []) + [
            a for att in verify.get("attestations", []) for a in att.get("attestors", [])
        ]:
            for entry in attestors.get("entries", []):
                keyless = entry.get("keyless", {})
                check(
                    keyless.get("subject", "").endswith(expected_identity_suffix),
                    f"{name}: keyless subject pins {expected_identity_suffix}",
                )
                check(
                    keyless.get("issuer") == expected_issuer,
                    f"{name}: keyless issuer is the GitHub token issuer",
                )

        # No GCP registries anywhere in the rendered rule
        serialized = str(rule)
        check(
            ".pkg.dev" not in serialized and "google" not in serialized.lower(),
            f"{name}: no GCP registry leakage",
        )

    # 5. Provenance JMESPath conditions
    provenance = rules["verify-provenance-attestation"]["verifyImages"][0]
    conditions = provenance["attestations"][0]["conditions"][0]["all"]
    actual = {(c["key"], c["value"]) for c in conditions}
    expected = {
        ("{{ invocation.configSource.entryPoint }}", expected_entrypoint),
        ("{{ builder.id }}", "https://github.com/actions/runner"),
        (
            "{{ invocation.configSource.uri }}",
            "git+https://github.com/devSatym/gcp-supply-chain-security@refs/heads/main",
        ),
    }
    check(actual == expected, "provenance JMESPath conditions match the attestation contract")

    # Kyverno workload identity values
    sa_annotations = values["admissionController"]["rbac"]["serviceAccount"]["annotations"]
    check(
        sa_annotations.get("azure.workload.identity/client-id")
        == RENDER_VARS["kyverno_client_id"],
        "values.yaml annotates the Kyverno ServiceAccount with the rendered client id",
    )
    check(
        values["admissionController"]["podLabels"].get("azure.workload.identity/use") == "true",
        "values.yaml labels Kyverno admission pods for Azure Workload Identity",
    )

    # 6. Fixtures are inside the policy selector and registry-clean
    digest_re = re.compile(r"@[a-zA-Z0-9]+:[0-9a-f]{64}$")
    for fixture in sorted(FIXTURE_DIR.glob("*.yaml")):
        doc = yaml.safe_load(fixture.read_text())
        podspec = doc["spec"]
        images = [
            c["image"]
            for field in ("initContainers", "containers", "ephemeralContainers")
            for c in podspec.get(field, [])
        ]
        check(bool(images), f"{fixture.name}: declares at least one container image")
        for image in images:
            inside = image.startswith(APP_IMAGE_PREFIX + "@") or image.startswith(
                APP_IMAGE_PREFIX + ":"
            )
            check(inside, f"{fixture.name}: image {image} is inside the policy imageReferences")
            if image.startswith(APP_IMAGE_PREFIX + "@"):
                check(
                    bool(digest_re.search(image)),
                    f"{fixture.name}: digest reference {image} is well formed",
                )
            check(
                ".pkg.dev" not in image and "google" not in image.lower() and "gcr.io" not in image,
                f"{fixture.name}: image {image} has no GCR/GAR leakage",
            )

    # The invalid-trust fixture is paired with a test-only policy that
    # deliberately names the wrong signer workflow and an untrusted source
    # ref. Keep this negative contract separate from the production identity
    # consistency checks above.
    invalid_policy = yaml.safe_load(INVALID_POLICY.read_text())
    invalid_rule = invalid_policy["spec"]["rules"][0]
    invalid_selector = invalid_rule["match"]["any"][0]["resources"]["selector"]["matchLabels"]
    check(
        invalid_policy["spec"]["validationFailureAction"] == "Enforce"
        and invalid_policy["spec"]["background"] is False,
        "invalid-trust policy is a foreground Enforce-only negative test",
    )
    check(
        invalid_selector == {"supply-chain-security-test": "invalid-trust"},
        "invalid-trust policy selects only its dedicated fixture",
    )
    invalid_verify = invalid_rule["verifyImages"][0]
    invalid_serialized = str(invalid_policy)
    check(
        "not-the-signing-workflow.yml@refs/heads/main" in invalid_serialized,
        "invalid-trust policy contains a deliberately wrong signer workflow",
    )
    check(
        "@refs/heads/feature/untrusted" in invalid_serialized,
        "invalid-trust policy contains a deliberately untrusted provenance ref",
    )
    check(
        invalid_verify.get("verifyDigest") is True
        and invalid_verify.get("required") is True
        and invalid_verify.get("mutateDigest") is False,
        "invalid-trust negative test remains digest-only and fail-closed",
    )

    # 7. Identity consistency across every Azure consumer
    full_identity_re = re.compile(r"\.github/workflows/[a-zA-Z0-9_-]+\.yml(?:\.yml)?@refs/heads/main")
    for path in IDENTITY_FILES:
        text = path.read_text()
        tokens = set(full_identity_re.findall(text))
        bad = [t for t in tokens if not t.endswith(expected_identity_suffix)]
        check(not bad, f"{path.relative_to(REPO)}: identity strings pin {expected_identity_suffix} ({bad or 'ok'})")
        if tokens:
            check(
                expected_issuer in text,
                f"{path.relative_to(REPO)}: GitHub OIDC issuer present alongside identity strings",
            )

    print()
    if failures:
        print(f"FAILED: {len(failures)} contract check(s) did not pass.", file=sys.stderr)
        return 1
    print("All Azure policy contract checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
