apiVersion: v1
kind: Pod
metadata:
  name: test-init-unsigned
  labels:
    test: mixed-signed-unsigned
spec:
  initContainers:
    - name: unsigned-init
      image: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo:unsigned-test
      command: ["sh", "-c", "echo init done"]
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
  containers:
    - name: signed-main
      image: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo@sha256:32a90d832fdf76794fa5477e42e1fdcec28c9eb6e0deee48ad466d1f7d9fc563
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
  restartPolicy: Never
