apiVersion: v1
kind: Pod
metadata:
  name: test-mixed-containers
  namespace: default
spec:
  initContainers:
    - name: unsigned-init-container
      image: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo:unsigned-test
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10001
  containers:
    - name: signed-container
      image: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo@sha256:32a90d832fdf76794fa5477e42e1fdcec28c9eb6e0deee48ad466d1f7d9fc563
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10001
