apiVersion: v1
kind: Pod
metadata:
  name: test-invalid-trust
  namespace: default
  labels:
    supply-chain-security-test: invalid-trust
spec:
  containers:
    - name: signed-image-with-invalid-trust-expectation
      image: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo@sha256:32a90d832fdf76794fa5477e42e1fdcec28c9eb6e0deee48ad466d1f7d9fc563
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10001
  restartPolicy: Never
