replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/valiant-house-502004-k2/supply-chain-security/supply-chain-demo
  digest: sha256:32a90d832fdf76794fa5477e42e1fdcec28c9eb6e0deee48ad466d1f7d9fc563
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
