apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity.enforce | quote }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity.audit | quote }}
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity.warn | quote }}
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
